### ISSUE TITLE
게시판 희망사항

### ISSUE THREAD

**Issue by MinGH0311** [parksjin01/2017-#14]
##글쓰기
1. 공지사항
공지사항에는 아예 글쓰기권한이 처음부터 없었으면 합니다
2. 글쓰기 후 코멘트
코멘트 위치가 위쪽에 위치했으면 합니다.
3. 코멘트
자유게시판에서 글쓰기를 누르면 자유게시판, Q&A에서 글쓰기를 누르면 코멘트가 Q&A로 디폴트값이 되어있으면 좋겠습니다.

**Comment by parksjin01** [comment]
All board bug fixed
