### ISSUE TITLE
에러 모음

### ISSUE THREAD

**Issue by MinGH0311** [parksjin01/2017-#29]
~~아이디 중복 확인 x(아이디 변경창에서)~~
~~단어 채점  단어 하나 클릭후 채점하면 에러~~
~~영어외에 다른단어 시험볼때 단어시험개수가 20개가 아닌 부족한 경우가있습니다.~~
~~__좋아요/싫어요__ 단어 추천/비추천했는데도 알림이 없습니다.~~
~~비공개버튼 -> 설정 (무반응)~~
~~마이페이지의 설정 범위를 설정해도 반영되지 않습니다.~~
~~좋아요/싫어요 좋아요 만 삭제 후 싫어요의 모든 단어들이 삭제되어있습니다.~~
~~좋아요/싫어요 중 1개만 전부 삭제해도 창이 열리지 않습니다.~~
~~듣기 자막을 잘못 찾아오는 경우가 있습니다.~~
듣기 빈칸제출시 오답처리 안되어있음
~~댓글 추천/비추천기능 누를경우 attributeerror~~
~~타인의 유저페이지 접속 후 게시판>댓글 클릭시 IndexError~~
~~타인의 유저페이지 접속 후 게시판>추천한게시글 클릭시 DoesNotExist~~

**Comment by parksjin01** [comment]
I think I solved 3rd problem, but there can be occur same error, If you get same error than write issue on project

**Comment by parksjin01** [comment]
All error is fixed
