### ISSUE TITLE
에러 모음 #2

### ISSUE THREAD

**Issue by MinGH0311** [parksjin01/2017-#30]
~~마이페이지>단어>좋아요!/싫어요! 부분 사용자추가단어부분이 빠져있습니다~~
~~좋아요!/싫어요! 가 작동하지 않습니다(일본어test)~~
~~단어 test가 그냥 엔터입력시 DoesNotError~~
~~단어추가 후 오른쪽상단탭이 통째로 사라졌습니다.(/add/vocabulary/)~~
~~단어추가 후 마이페이지에서 제대로 추가되어있지 않습니다.~~

**Comment by parksjin01** [comment]
Last error, I'll add notice pop up that already exist words in db won't be added in new word

**Comment by parksjin01** [comment]
All error is fixed
