### ISSUE TITLE
Change ID/PW 창

### ISSUE THREAD

**Issue by MinGH0311** [parksjin01/2017-#6]
1. ID창 입력시 ID 중복이 되는지 체크하는 체크박스가 없습니다.
        __ID중복입력이 가능__
2. 또한 _Password_ 와 _Check Password_ 가 다르게 입력 후 변경을 누르면 홈으로 돌아가지는 현상이 발생하는데,
Change ID/PW창에 계속 머물렀으면 합니다.

**Comment by parksjin01** [comment]
I added
